secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  secretkeybase:
    file: ./secrets/.secretkeybase
  databaseurl:
    file: ./secrets/.databaseurl

services:
  db:
    image: postgres:15.2
    secrets:
      - postgrespassword
    ports:
      - ${POSTGRES_PORT:-5432}
    healthcheck:
      test: [CMD, pg_isready, --username=postgres]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    command: bash -c "bin/migrate && bin/server"
    image: ${WEB_IMAGE:-ghcr.io/robertcgouge/kanban:latest}
    secrets:
      - databaseurl
      - secretkeybase
    deploy:
      replicas: ${WEB_REPLICAS:-1}
      placement:
        preferences:
          - spread: node.hostname
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: localhost
    ports:
      - 4000:4000

volumes:
  db_data:
